Return-Path: <linux-kernel-owner@vger.kernel.org>
X-Original-To: lists+linux-kernel@lfdr.de
Delivered-To: lists+linux-kernel@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [209.132.180.67])
	by mail.lfdr.de (Postfix) with ESMTP id 865EF1A33C8
	for <lists+linux-kernel@lfdr.de>; Thu,  9 Apr 2020 14:08:02 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1726620AbgDIMH5 (ORCPT <rfc822;lists+linux-kernel@lfdr.de>);
        Thu, 9 Apr 2020 08:07:57 -0400
Received: from mx2.suse.de ([195.135.220.15]:51232 "EHLO mx2.suse.de"
        rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
        id S1725971AbgDIMH5 (ORCPT <rfc822;linux-kernel@vger.kernel.org>);
        Thu, 9 Apr 2020 08:07:57 -0400
X-Virus-Scanned: by amavisd-new at test-mx.suse.de
Received: from relay2.suse.de (unknown [195.135.220.254])
        by mx2.suse.de (Postfix) with ESMTP id 634A3AE7B;
        Thu,  9 Apr 2020 12:07:56 +0000 (UTC)
Date:   Thu, 09 Apr 2020 14:07:56 +0200
Message-ID: <s5htv1soo9v.wl-tiwai@suse.de>
From:   Takashi Iwai <tiwai@suse.de>
To:     Xu Wang <vulab@iscas.ac.cn>
Cc:     <perex@perex.cz>, <tiwai@suse.com>, <tglx@linutronix.de>,
        <allison@lohutok.net>, <alsa-devel@alsa-project.org>,
        <linux-kernel@vger.kernel.org>
Subject: Re: [PATCH] ALSA: ctxfi: Remove unnecessary cast in kfree
In-Reply-To: <20200409112052.13402-1-vulab@iscas.ac.cn>
References: <20200409112052.13402-1-vulab@iscas.ac.cn>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
Content-Type: text/plain; charset=US-ASCII
Sender: linux-kernel-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-kernel.vger.kernel.org>
X-Mailing-List: linux-kernel@vger.kernel.org

On Thu, 09 Apr 2020 13:20:52 +0200,
Xu Wang wrote:
> 
> Remove unnecassary casts in the argument to kfree.
> 
> Signed-off-by: Xu Wang <vulab@iscas.ac.cn>

Applied, thanks.


Takashi
