Return-Path: <linux-kernel-owner@vger.kernel.org>
X-Original-To: lists+linux-kernel@lfdr.de
Delivered-To: lists+linux-kernel@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id 8564F2C2886
	for <lists+linux-kernel@lfdr.de>; Tue, 24 Nov 2020 14:45:31 +0100 (CET)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S2388550AbgKXNno (ORCPT <rfc822;lists+linux-kernel@lfdr.de>);
        Tue, 24 Nov 2020 08:43:44 -0500
Received: from mx2.suse.de ([195.135.220.15]:45354 "EHLO mx2.suse.de"
        rhost-flags-OK-OK-OK-OK) by vger.kernel.org with ESMTP
        id S2388496AbgKXNnm (ORCPT <rfc822;linux-kernel@vger.kernel.org>);
        Tue, 24 Nov 2020 08:43:42 -0500
X-Virus-Scanned: by amavisd-new at test-mx.suse.de
Received: from relay2.suse.de (unknown [195.135.221.27])
        by mx2.suse.de (Postfix) with ESMTP id ECD95AC66;
        Tue, 24 Nov 2020 13:43:40 +0000 (UTC)
Date:   Tue, 24 Nov 2020 14:43:40 +0100
Message-ID: <s5hwnyarhtf.wl-tiwai@suse.de>
From:   Takashi Iwai <tiwai@suse.de>
To:     Jian-Hong Pan <jhp@endlessos.org>
Cc:     Takashi Iwai <tiwai@suse.com>, Kailang Yang <kailang@realtek.com>,
        alsa-devel@alsa-project.org, linux-kernel@vger.kernel.org,
        linux@endlessos.org
Subject: Re: [PATCH] ALSA: hda/realtek: Enable headset of ASUS UX482EG & B9400CEA with ALC294
In-Reply-To: <20201124092024.179540-1-jhp@endlessos.org>
References: <20201124092024.179540-1-jhp@endlessos.org>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
Content-Type: text/plain; charset=US-ASCII
Precedence: bulk
List-ID: <linux-kernel.vger.kernel.org>
X-Mailing-List: linux-kernel@vger.kernel.org

On Tue, 24 Nov 2020 10:20:25 +0100,
Jian-Hong Pan wrote:
> 
> Some laptops like ASUS UX482EG & B9400CEA's headset audio does not work
> until the quirk ALC294_FIXUP_ASUS_HPE is applied.
> 
> Signed-off-by: Jian-Hong Pan <jhp@endlessos.org>

Thanks, applied now.


Takashi
